[bugfix] Postgres ignored tables do not contain " "
kitloong/laravel-migrations-generator pull request #49
Opened 2021-10-05 05:16 UTC by rennokki

For some reason, when using the `--ignore` command in Postgres, the `$tables` in `filterTables()` look like this:

```php
array:2 [
  0 => ""Daily_Consumables""
  1 => ""Daily_Personnel""
]
```

This fixes it, but I assume it needs to have a check for Postgres, as currently, I'm unaware if this persists for other database connection drivers as well.

2021-10-05 13:53 UTC, kitloong requested changes

2021-10-05 13:53 UTC, kitloong commented on src/MigrationsGenerator/MigrateGenerateCommand.php
> +            collect($this->getExcludedTables())->map(fn ($table) => '"'.$table.'"')->toArray(),
PostgreSQL adds `"` if table name is `Uppercase` or contains special characters such as `-`.
I am not sure if it is okay to padding `"` into every table name, my main concern is what is the side effect of this solution.

On second thought, if you provide double quote from command:
```
php artisan migrate:generate --ignore=\"Daily_Consumables\"
```

Will that fix the problem?

2021-10-05 17:50 UTC, closed without merging

2021-10-05 17:50 UTC, rennokki commented
Closed this as it seems like it was a special case where the tables were capitalized. 😢 Everything works as expected.

2021-10-31 03:09 UTC, kitloong commented
Revisited and updated `--ignore` to support name with or without `"` d5120e3